spring.profiles.active: local

spring:
  data:
    mongodb:
      database: qwerqwer


---

spring.config.activate.on-profile: local

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27000/short_url?authSource=admin
      database: short_url